common:
  dt: 0.002
  joint_cnt: 22
  stiffness: [
    2, 2,
    5, 5, 5, 5,
    5, 5, 5, 5,
    80, 80, 80, 80, 25, 25,
    80, 80, 80, 80, 25, 25
  ]
  damping: [
    0.2, 0.2,
    0.5, 0.5, 0.5, 0.5,
    0.5, 0.5, 0.5, 0.5,
    4, 4, 4, 4, 1, 1,
    4, 4, 4, 4, 1, 1
  ]
  default_qpos: [
    0, 0,
    0.2, -1.35, 0, -0.5,
    0.2, 1.35, 0, 0.5,
    -0.2, 0, 0, 0.4, -0.25, 0,
    -0.2, 0, 0, 0.4, -0.25, 0
  ]
  torque_limit: [
    7, 7,
    10, 10, 10, 10,
    10, 10, 10, 10,
    30, 20, 20, 40, 20, 15,
    30, 20, 20, 40, 20, 15
  ]

policy:
  policy_path: "./models/model_4600.pt"
  num_actions: 12
  num_observations: 54
  gait_frequency: 1

  normalization:
    gravity: 1.0
    lin_vel: 1.0
    ang_vel: 1.0
    gait_frequency: 1.0
    foot_yaw: 1.0
    foot_yaw: 1.0
    body_pitch_target: 1.0
    body_roll_target: 1.0
    feet_offset_x_target: 1.0
    feet_offset_y_target: 1.0
    dof_pos: 1.0
    dof_vel: 0.1
    clip_actions: 1.0

  control:
    action_scale: 1.
    decimation: 10

mech:
  parallel_mech_indexes: [14, 15, 20, 21]

prepare:
  stiffness: [
    2, 2,
    5, 5, 5, 5,
    5, 5, 5, 5,
    80, 80, 80, 80, 25, 25,
    80, 80, 80, 80, 25, 25
  ]
  damping: [
    0.2, 0.2,
    0.5, 0.5, 0.5, 0.5,
    0.5, 0.5, 0.5, 0.5,
    1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1
  ]
  default_qpos: [
    0.0,  0.0,
    0.25, -1.4, 0.0, -0.5,
    0.25, 1.4, 0.0, 0.5,
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
  ]
